apiVersion: v2
name: core-extensions
description: A Helm chart for Kubernetes core resources extensions
type: application
version: 1.0.0
appVersion: 1.0.0


icon: https://raw.githubusercontent.com/emberstack/helm-charts/main/assets/helm_icon_generic.png
keywords:
- configmap
- secret
- core
- kubernetes
home: https://github.com/emberstack/helm-charts
sources:
- https://github.com/emberstack/helm-charts
maintainers:
- name: emberstack
  email: helm-charts@emberstack.com